// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PekerStore.Data.Concrete;

#nullable disable

namespace PekerStore.Web.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20250909110157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PekerStore.Data.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Novel",
                            Description = "Dostoyevski Book",
                            Name = "Crime and Punishment",
                            Price = 10m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Novel",
                            Description = "Tolstoy Book",
                            Name = "Anna Karenina",
                            Price = 20m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Novel",
                            Description = "Dostoyevski Book",
                            Name = "The Double",
                            Price = 10m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Fantastic",
                            Description = "GRM Book",
                            Name = "Game of Thrones",
                            Price = 30m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Novel",
                            Description = "Tarık Buğra Book",
                            Name = "Küçük Ağa",
                            Price = 40m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
